imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   "%database_driver%"
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
#        # if using pdo_sqlite as your database driver:
#        #   1. add the path in parameters.yml
#        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
#        #   2. Uncomment database_path in parameters.yml.dist
#        #   3. Uncomment next line:
#        #     path:     "%database_path%"
#
#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: simple_acl_project
    document_managers:
        default:
            auto_mapping: true

fos_user:
    db_driver: mongodb # other valid values are orm, 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: SimpleAcl\Bundle\CoreBundle\Document\User

fos_rest:
    disable_csrf_role: ROLE_API

fos_oauth_server:
    db_driver: mongodb       # Driver availables: orm, mongodb, or propel
    client_class:        SimpleAcl\Bundle\ApiBundle\Document\Client
    access_token_class:  SimpleAcl\Bundle\ApiBundle\Document\AccessToken
    refresh_token_class: SimpleAcl\Bundle\ApiBundle\Document\RefreshToken
    auth_code_class:     SimpleAcl\Bundle\ApiBundle\Document\AuthCode

    service:
        user_provider: fos_user.user_manager

simple_acl_core:
    db_driver: mongodb

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

jms_serializer:
    metadata:
        directories:
            fosub:
                namespace_prefix: "FOS\\UserBundle"
                path: @SimpleAclApiBundle/Resources/config/serializer/fosub
            simpleaclcore:
                namespace_prefix: "SimpleAcl\\Bundle\\CoreBundle"
                path: @SimpleAclApiBundle/Resources/config/serializer/simpleaclcore
            component:
                namespace_prefix: "SimpleAcl\\Compoment\\Model"
                path: @SimpleAclApiBundle/Resources/config/serializer/component
