SimpleAcl\Bundle\CoreBundle\Document\User:
    exclusion_policy: ALL
    properties: ~
#    relations:
#        - rel: profile
#          href:
#              route: kfc_api_profile_show
#              parameters:
#                  id: expr(object.getProfile().getId())
#          embedded:
#              content: expr(object.getProfile())
#              exclusion:
#                  groups: [ profile, profile_full ]
#          exclusion:
#              groups: [user_full]
#              exclude_if: expr(object.getProfile() === null)
