SimpleAcl\Component\Model\Product:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
        name:
            expose: true
            type: string
        description:
            expose: true
            type: string
        price:
            expose: false
    relations:
        - rel: self
          href:
              route: simple_acl_product_get
              parameters:
                  id: expr(object.getId())
